# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'StarredRepositories' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StarredRepositories

  pod 'Moya/RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'Kingfisher'
  pod 'SnapKit', '~> 5.0.0'

  target 'StarredRepositoriesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StarredRepositoriesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
